name: boksklapps
description: Boxing Cardio App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  assets_audio_player: ^3.0.6
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^7.0.0-dev.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  flutter_riverpod: ^2.1.3
  google_fonts: ^4.0.1
  logger: ^1.1.0  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/GIF/
    - assets/PNG/
    - assets/WAV/
