name: boksklapps
description: "BOKSklapps. A boxing cardio PWA."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  logger: ^2.0.2+1
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/GIF/
