// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Default [FirebaseOptions] for use with your Firebase apps on Android.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// FirebaseOptions for use with your Firebase apps on the web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCTl1JZq_JqX39VCBjq69_CsBvJFEBD6Q',
    appId: '1:186836765191:web:5604e98fa31dbdb31938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    authDomain: 'boksklapps.firebaseapp.com',
    storageBucket: 'boksklapps.appspot.com',
    measurementId: 'G-TR1L7C1MEC',
  );

  /// FirebaseOptions for use with your Firebase apps on Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVkdSiG7KAd9iHXqJ-7SbWXitAWM3w8I',
    appId: '1:186836765191:android:14694af496e734a81938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
  );

  /// FirebaseOptions for use with your Firebase apps on iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0tv_ZwteHre2fJkh-XQi4_fnal-oYwI',
    appId: '1:186836765191:ios:111c003a9eee05b21938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
    iosClientId:
        '186836765191-shn3gcc847djr8picte08nh61992a44n.apps.googleusercontent.com',
    iosBundleId: 'nl.plotsklapps.boksklapps',
  );

  /// FirebaseOptions for use with your Firebase apps on macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0tv_ZwteHre2fJkh-XQi4_fnal-oYwI',
    appId: '1:186836765191:ios:111c003a9eee05b21938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
    iosClientId:
        '186836765191-shn3gcc847djr8picte08nh61992a44n.apps.googleusercontent.com',
    iosBundleId: 'nl.plotsklapps.boksklapps',
  );
}
