// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCTl1JZq_JqX39VCBjq69_CsBvJFEBD6Q',
    appId: '1:186836765191:web:5604e98fa31dbdb31938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    authDomain: 'boksklapps.firebaseapp.com',
    storageBucket: 'boksklapps.appspot.com',
    measurementId: 'G-TR1L7C1MEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVkdSiG7KAd9iHXqJ-7SbWXitAWM3w8I',
    appId: '1:186836765191:android:e1dd815e69d35a1b1938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0tv_ZwteHre2fJkh-XQi4_fnal-oYwI',
    appId: '1:186836765191:ios:ce13bac94275cf5e1938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
    iosBundleId: 'dev.plotsklapps.boksklapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd0tv_ZwteHre2fJkh-XQi4_fnal-oYwI',
    appId: '1:186836765191:ios:aa8d873cbb0928831938a2',
    messagingSenderId: '186836765191',
    projectId: 'boksklapps',
    storageBucket: 'boksklapps.appspot.com',
    iosBundleId: 'dev.plotsklapps.boksklapps.RunnerTests',
  );
}
